name: PR Check

on:
  pull_request:
    branches:
      - main

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: PR Triggered
        run: echo "Pull Request workflow executed successfully"
